name: Deploy Mac

on:
  release:
    types:
      - published
env:
  GRT:  ${{ secrets.GITHUB_TOKEN }}
  GT:  ${{ secrets.GT }}
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm install --location=global npm
      - run: npm install -f
      - run: npm run build:mac
      - run: node upload.mac.js
