name: Deploy Mac

on:
  release:
    types:
      - published
env:
  GRT:  ${{ secrets.GITHUB_TOKEN }}
  GT:  ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: rm package-lock.json
      - run: npm install -f
      - run: export GH_TOKEN=${{ secrets.GITHUB_TOKEN }} && npm run build:mac
      - run: export GH_TOKEN=${{ secrets.GITHUB_TOKEN }} && node upload.mac.js
        env:
          GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GT: ${{ secrets.GITHUB_TOKEN }}
