name: Deploy Linux

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - uses: snapcore/action-build@v1
      id: build
    - run: npm install --location=global npm
    - run: npm install -f
    - name: get-npm-version

    - uses: martinbeentjes/npm-get-version-action@master
      id: pv
      
    - uses: snapcore/action-publish@v1
    - run: npm install --location=global npm
    - run: npm install -f
    - run: export PACKAGE_VERSION=${{ steps.pv.outputs.current-version }} && npm run deploy:desktop:snap
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}

    #   uses: martinbeentjes/npm-get-version-action@master
    # - name: Install Snapcraft
    #   uses: samuelmeuli/action-snapcraft@v1
    #   with:
    #     snapcraft_token: ${{ secrets.STORE_LOGIN }}
    #     skip_install: false
    
    #   env:
    #     GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
