name: Deploy Windows

on:
  release:
    types:
      - published

env:
  GRT: ${{ secrets.GITHUB_TOKEN }}
  GT: ${{ secrets.GT }}
defaults:
  run:
    shell: powershell
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm install --location=global npm
      - run: npm install -f
      - run: npm run build:win
        env:
          GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GT: ${{ secrets.GITHUB_TOKEN }}
      - run: node upload.win.js
        env:
          GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GT: ${{ secrets.GITHUB_TOKEN }}
        
